import * as MUSICANS_WITH_ALBUMS from "./with-albums";

export const MUSICIANS: IMusicians = {
  ...MUSICANS_WITH_ALBUMS,
  // 123
  "100_GECS": { name: "100 gecs" },
  // A
  AURORA: { name: "Aurora" },
  ACADEMY_IS_THE: { name: "Academy Is..., The" },
  ALESSIA_CARA: { name: "Alessia Cara" },
  ALEX_CHAPMAN: { name: "Alex Chapman" },
  ALL_AMERICAN_REJECTS_THE: { name: "All-American Rejects, The" },
  ALL_TIME_LOW: { name: "All Time Low" },
  ALMA: { name: "Alma" },
  AMOS_LEE: { name: "Amos Lee" },
  ANNA_OF_THE_NORTH: { name: "Anna of the North" },
  ANASTACIA: { name: "Anastacia" },
  ANNE_MARIE: { name: "Anne-Marie" },
  AQUILO: { name: "Aquilo" },
  AUDITION_THE: { name: "Audition, The" },
  // B
  BAAUER: { name: "Baauer" },
  BANANARAMA: { name: "Bananarama" },
  BASTILLE: { name: "Bastille" },
  BAYNK: { name: "BAYNK" },
  BEARS_DEN: { name: "Bear's Den" },
  BECKY_MILLS_HILL: { name: "Becky Hill" },
  BETSY: { name: "Betsy" },
  BETTY_WHO: { name: "Betty Who" },
  BICEP: { name: "Bicep" },
  BILLIE_EILISH: { name: "Billie Eilish" },
  BLACK_KIDS: { name: "Black Kids" },
  B_O_B: { name: "B.o.B" },
  BONDAX: { name: "Bondax" },
  BON_IVER: { name: "Bon Iver" },
  BONTAN: { name: "Bontan" },
  BORNS: { name: "BØRNS" },
  BOYS_LIKE_GIRLS: { name: "Boys Like Girls" },
  BLONDE: { name: "Blonde" },
  BREACH: { name: "Breach" },
  BRIGITTE_APHRODITE: { name: "Brigitte Aphrodite" },
  BRITNEY_SPEARS: { name: "Britney Spears" },
  BROODS: { name: "Broods" },
  BULOW: { name: "bülow" },
  // C
  CAMILA_CABELLO: { name: "Camila Cabello" },
  CARLY_RAE_JEPSEN: { name: "Carly Rae Jepsen" },
  CARL_COX: { name: "Carl Cox" },
  CELESTE: { name: "Celeste" },
  CHARLI_ADAMS: { name: "Charli Adams" },
  CHARLOTTE_CHURCH: { name: "Charlotte Church" },
  CHELSEA_CUNNINGHAM_CUTLER: { name: "Chelsea Cutler" },
  CHEMICAL_BROTHERS_THE: { name: "Chemical Brothers, The" },
  CHERYL: { name: "Cheryl" },
  CHLOE_WHITE_X_HALLE: { name: "Chloe x Halle" },
  CHRISTINE_AND_THE_QUEENS: { name: "Christine and the Queens" },
  CHRVCHES: { name: "CHVRCHES" },
  CLAIRO: { name: "Clairo" },
  CLEAN_BANDIT: { name: "Clean Bandit" },
  COBRA_STARSHIP: { name: "Cobra Starship" },
  CODE_THE: { name: "Code, The" },
  CRUEL_YOUTH: { name: "Cruel Youth", favourite: true },
  CUTE_IS_WHAT_WE_AIM_FOR: { name: "Cute Is What We Aim for" },
  CYRIL_HAHN: { name: "Cyril Hahn" },
  // D
  DANIEL_AVERY: { name: "Daniel Avery" },
  DAUGHTER: { name: "Daughter" },
  DAVID_RODIGAN: { name: "David Rodigan" },
  DIPLO: { name: "Diplo" },
  DISCLOSURE: { name: "Disclosure" },
  DIZZEE_RASCAL: { name: "Dizzee Rascal" },
  DRUMS_THE: { name: "Drums, The" },
  DUKE_DUMONT: { name: "Duke Dumont" },
  DUSKY: { name: "Dusky", favourite: true },
  DYLAN: { name: "Dylan" },
  // E
  EARTHEATER: { name: "Eartheater" },
  EATS_EVERYTHING: { name: "Eats Everything" },
  ELDERBROOK: { name: "Elderbrook" },
  ELIZA_DOOLITTLE: { name: "Eliza Doolittle" },
  ELLA_EYRE: { name: "Ella Eyre" },
  EMAROSA: { name: "Emarosa" },
  // F
  FALL_OUT_BOY: { name: "Fall Out Boy" },
  FLEETWOOD_MAC: { name: "Fleetwood Mac" },
  FLIGHT_FACILITIES: { name: "Flight Facilities" },
  FOREVER_THE_SICKEST_KIDS: { name: "Forever the Sickest Kids" },
  FOURS: { name: "Fours" },
  FOUR_TET: { name: "Four Tet" },
  FOXES: { name: "Foxes" },
  FRANCES: { name: "Frances" },
  FRANCIS_AND_THE_LIGHTS: { name: "Francis and the Lights" },
  FRANK_OCEAN: { name: "Frank Ocean" },
  FREYA_RIDINGS: { name: "Freya Ridings" },
  FRIDAY_NIGHT_BOYS_THE: { name: "Friday Night Boys, The" },
  FRIEND_WITHIN: { name: "Friend Within" },
  // G
  GEORGE_EZRA: { name: "George Ezra" },
  GEORGIA: { name: "Georgia" },
  G_FLIP: { name: "G Flip" },
  GLOWIE: { name: "Glowie" },
  GORGON_CITY: { name: "Gorgon City" },
  GRACEY: { name: "GRACEY" },
  GREEN_VELVET: { name: "Green Velvet" },
  GROOVE_ARMADA: { name: "Groove Armada" },
  GRYFFIN: { name: "Gryffin" },
  GYM_CLASS_HEROES: { name: "Gym Class Heroes" },
  // H
  HALSEY: { name: "Halsey" },
  HANNAH_WANTS: { name: "Hannah Wants" },
  HAUX: { name: "Haux" },
  HEIDI: { name: "Heidi" },
  HEY_MONDAY: { name: "Hey Monday" },
  HOLLY_HUMBERSTONE: { name: "Holly Humberstone" },
  HORSE_MEAT_DISCO: { name: "Horse Meat Disco" },
  // I
  INCOGNITO: { name: "Incognito" },
  // J
  JAMES_BAY: { name: "James Bay" },
  JAMES_BLAKE: { name: "James Blake" },
  JAMIE_JONES: { name: "Jamie Jones" },
  JAMIE_T: { name: "Jamie T" },
  JAMIE_XX: { name: "Jamie xx" },
  JAX_JONES: { name: "Jax Jones" },
  JAY_Z: { name: "JAY Z" },
  JEREMY_ZUCKER: { name: "Jeremy Zucker" },
  JESS_GLYNNE: { name: "Jess Glynne" },
  JESSIE_WARE: { name: "Jessie Ware" },
  JOE_GODDARD: { name: "Joe Goddard" },
  JOHNNY_MARR: { name: "Johnny Marr" },
  JONAS_BLUE: { name: "Jonas Blue" },
  JONES: { name: "Jones" },
  JORIS_VOORN: { name: "Joris Voorn" },
  JORJA_SMITH: { name: "Jorja Smith" },
  JOSH_BUTLER: { name: "Josh Butler" },
  JOY_ORBISON: { name: "Joy Orbison" },
  JOSEF_SALVAT: { name: "Josef Salvat" },
  JULIA_MICHAELS: { name: "Julia Michaels" },
  JULIO_BASHMORE: { name: "Julio Bashmore" },
  JUSTIN_BIEBER: { name: "Justin Bieber" },
  JUSTIN_MARTIN: { name: "Justin Martin" },
  // K
  KAH_LO: { name: "Kah-Lo" },
  KANYE_WEST: { name: "Kanye West" },
  KAYTRANADA: { name: "Kaytranada" },
  KESHA: { name: "Kesha" },
  KIASMOS: { name: "Kiasmos" },
  KIDNAP: { name: "Kidnap" },
  KIDS_IN_GLASS_HOUSES: { name: "Kids In Glass Houses" },
  KILLERS_THE: { name: "Killers, The" },
  KOLSCH: { name: "Kölsch" },
  KYGO: { name: "Kygo" },
  // L
  LADY_STARLIGHT: { name: "Lady Starlight" },
  LA_ROUX: { name: "La Roux" },
  LAUV: { name: "Lauv" },
  L_DEVINE: { name: "L Devine" },
  LELAND: { name: "Leland" },
  LILY_ALLEN: { name: "Lily Allen" },
  LITANY: { name: "Litany" },
  LITTLE_COMETS: { name: "Little Comets" },
  LITTLE_DRAGON: { name: "Little Dragon" },
  LONDON_GRAMMAR: { name: "London Grammar" },
  LUCY_ROSE: { name: "Lucy Rose" },
  LYKKE_LI: { name: "Lykke Li" },
  LYVES: { name: "Lyves" },
  // M
  MACEO_PLEX: { name: "Maceo Plex" },
  MALLRAT: { name: "Mallrat" },
  MAGGIE_ROGERS: { name: "Maggie Rogers" },
  MAINE_THE: { name: "Maine, The" },
  MAJOR_LAZER: { name: "Major Lazer" },
  MARY_J_BLIGE: { name: "Mary J. Blige" },
  MARTIN_SOLVEIG: { name: "Martin Solveig" },
  MELANIE_MARTINEZ: { name: "Melanie Martinez" },
  METRO_STATION: { name: "Metro Station" },
  MICHAEL_KIWANUKA: { name: "Michael Kiwanuka" },
  MIDLAND: { name: "Midland" },
  MIGUEL: { name: "Miguel" },
  MIKE_POSNER: { name: "Mike Posner" },
  MILEY_CYRUS: { name: "Miley Cyrus" },
  MISHA_B: { name: "Misha B" },
  M_0: { name: "M.O" },
  MK: { name: "MK" },
  MNEK: { name: "MNEK" },
  MO: { name: "MØ" },
  MURA_MASA: { name: "Mura Masa" },
  // N
  NAAZ: { name: "Naaz" },
  NAO: { name: "Nao" },
  NASTY_CHERRY: { name: "Nasty Cherry" },
  NATASHA_BEDINGFIELD: { name: "Natasha Bedingfield" },
  NAVVY: { name: "Navvy" },
  NICKI_MINAJ: { name: "Nicki Minaj" },
  NOEL_GALLAGHERS_HIGH_FLYING_BIRDS: {
    name: "Noel Gallagher's High Flying Birds"
  },
  // O
  OH_ANNIE_OH: { name: "Oh Annie Oh" },
  OKAYWILL: { name: "okaywill" },
  // P
  PALE_WAVES: { name: "Pale Waves" },
  PALOMA_FAITH: { name: "Paloma Faith" },
  PAUL_WOOLFORD: { name: "Paul Woolford" },
  PET_SHOP_BOYS: { name: "Pet Shop Boys" },
  PHILIP_GEORGE: { name: "Philip George" },
  PRETENDERS: { name: "Pretenders" },
  // R
  RAINBOW_KITTEN_SURPRISE: { name: "Rainbow Kitten Surprise" },
  RALEIGH_RITCHIE: { name: "Raleigh Ritchie" },
  RALPH: { name: "Ralph" },
  RATIONALE: { name: "Rationale" },
  REDLIGHT: { name: "Redlight" },
  RINA_SAWAYAMA: { name: "Rina Sawayama" },
  RITON: { name: "Riton" },
  RIXTON: { name: "Rixton" },
  ROBINSON: { name: "Robinson" },
  ROBYN: { name: "Robyn" },
  ROMY: { name: "Romy" },
  ROOSEVELT: { name: "Roosevelt" },
  ROUTE_94: { name: "Route 94" },
  RUDIMENTAL: { name: "Rudimental" },
  RUFUS_DU_SOL: { name: "RÜFÜS DU SOL" },
  RYAN_BEATTY: { name: "Ryan Beatty" },
  // S
  SABRINA_CLAUDIO: { name: "Sabrina Claudio" },
  SAINT_JHN: { name: "SAINt JHN" },
  SAM_SMITH: { name: "Sam Smith" },
  SASHA_SLOAN: { name: "Sasha Sloan" },
  SBTRKT: { name: "SBTRKT" },
  SEEB: { name: "Seeb" },
  SEGA_BODEGA: { name: "Sega Bodega" },
  SEINABO_SEY: { name: "Seinabo Sey" },
  SEVDALIZA: { name: "Sevdaliza" },
  SIA: { name: "Sia" },
  SIGRID: { name: "Sigrid" },
  SISTER_SLEDGE: { name: "Sister Sledge" },
  SKY_FERREIRA: { name: "Sky Ferreira", favourite: true },
  SLIIMY: { name: "Sliimy" },
  SOFI_TUKKER: { name: "Sofi Tukker" },
  SOAK: { name: "SOAK" },
  SONIKKU: { name: "SONIKKU" },
  SOPHIE_ELLIS_BEXTOR: { name: "Sophie Ellis-Bextor" },
  SOUL_WAX: { name: "Soul Wax" },
  SMYTHS_THE: { name: "Smyths, The" },
  SPILL_CANVAS_THE: { name: "Spill Canvas, The" },
  SKREAM: { name: "Skream" },
  SUNDAY_GIRL: { name: "Sunday Girl" },
  // T
  TENSNAKE: { name: "Tensnake" },
  TEN_WALLS: { name: "Ten Walls" },
  TERROR_JR: { name: "Terror Jr" },
  TOM_ODELL: { name: "Tom Odell" },
  TORI_KELLY: { name: "Tori Kelly" },
  TOVE_LO: { name: "Tove Lo" },
  TULISA: { name: "Tulisa" },
  TWENTY_ONE_PILOTS: { name: "Twenty One Pilots" },
  TWO_FEET: { name: "Two Feet" },
  TYGA: { name: "Tyga" },
  // V
  VERITE: { name: "VÉRITÉ" },
  // W
  WE_THE_KINGS: { name: "We the Kings" },
  WILL_YOUNG: { name: "Will Young" },
  // X
  XX_THE: { name: "xx, The" },
  // Y
  YEARS_AND_YEARS: { name: "Years & Years" },
  YOU_ME_AT_SIX: { name: "You Me At Six" },
  YOUSEF: { name: "Yousef" },
  // Z
  ZARA_LARSSON: { name: "Zara Larsson" }
};
