export const MUSICIANS = {
  // 123
  "1975": "1975, The",
  "100_GECS": "100 gecs",
  // A
  AURORA: "Aurora",
  THE_ACADEMY_IS: "Academy Is..., The",
  ALESSIA_CARA: "Alessia Cara",
  ALEX_CHAPMAN: "Alex Chapman",
  ALL_AMERICAN_REJECTS: "All-American Rejects, The",
  ALLIE_X: "Allie X",
  ALL_TIME_LOW: "All Time Low",
  ALMA: "Alma",
  AMOS_LEE: "Amos Lee",
  ANNA_OF_THE_NORTH: "Anna of the North",
  ADELE: "Adele",
  ANASTACIA: "Anastacia",
  ANNE_MARIE: "Anne-Marie",
  AQUILO: "Aquilo",
  ARCTIC_MONKEYS: "Arctic Monkeys",
  ARIANA_GRANDA: "Ariana Grande",
  AUDITION: "Audition, The",
  // B
  BAAUER: "Baauer",
  BANANARAMA: "Bananarama",
  BANKS: "Banks",
  BASTILLE: "Bastille",
  BAYNK: "BAYNK",
  BEARS_DEN: "Bear's Den",
  BECKY_HILL: "Becky Hill",
  BEN_HOWARD: "Ben Howard",
  BETSY: "Betsy",
  BETTY_WHO: "Betty Who",
  BEYONCE: "Beyoncé",
  BICEP: "Bicep",
  BILLIE_EILISH: "Billie Eilish",
  BLACK_KIDS: "Black Kids",
  B_O_B: "B.o.B",
  BONDAX: "Bondax",
  BON_IVER: "Bon Iver",
  BONTAN: "Bontan",
  BORNS: "BØRNS",
  BOYS_LIKE_GIRLS: "Boys Like Girls",
  BLONDE: "Blonde",
  BREACH: "Breach",
  BRIGITTE_APHRODITE: "Brigitte Aphrodite",
  BRITNEY_SPEARS: "Britney Spears",
  BROODS: "Broods",
  BULOW: "bülow",
  // C
  CAMILA_CABELLO: "Camila Cabello",
  CARIBOU: "Caribou",
  CARLY_RAE_JEPSEN: "Carly Rae Jepsen",
  CARL_COX: "Carl Cox",
  CAROLINE_POLACHEK: "Caroline Polachek",
  CELESTE: "Celeste",
  CHARLI_ADAMS: "Charli Adams",
  CHARLI_XCX: "Charli XCX",
  CHARLOTTE_CHURCH: "Charlotte Church",
  CHELSEA_CUTLER: "Chelsea Cutler",
  CHEMICAL_BROTHERS: "Chemical Brothers, The",
  CHERYL: "Cheryl",
  CHRISTINE_AND_THE_QUEENS: "Christine and the Queens",
  CHRVCHES: "CHVRCHES",
  CLAIRO: "Clairo",
  CLEAN_BANDIT: "Clean Bandit",
  COBRA_STARSHIP: "Cobra Starship",
  CODE: "Code, The",
  CRUEL_YOUTH: { name: "Cruel Youth", favourite: true },
  CUTE_IS_WHAT_WE_AIM_FOR: "Cute Is What We Aim for",
  CYRIL_HAHN: "Cyril Hahn",
  // D
  DANIEL_AVERY: "Daniel Avery",
  DAUGHTER: "Daughter",
  DAVID_RODIGAN: "David Rodigan",
  DIPLO: "Diplo",
  DISCLOSURE: "Disclosure",
  DIZZEE_RASCAL: "Dizzee Rascal",
  DRUMS: "Drums, The",
  DUKE_DUMONT: "Duke Dumont",
  DUA_LIPA: "Dua Lipa",
  DUSKY: "Dusky",
  DYLAN: "Dylan",
  // E
  EARTHEATER: "Eartheater",
  EATS_EVERYTHING: "Eats Everything",
  ELDERBROOK: "Elderbrook",
  ELIZA_DOOLITTLE: "Eliza Doolittle",
  ELLA_EYRE: "Ella Eyre",
  ELLIE_GOULDING: "Ellie Goulding",
  EMAROSA: "Emarosa",
  // F
  FALL_OUT_BOY: "Fall Out Boy",
  FKA_TWIGS: "FKA twigs",
  FLEETWOOD_MAC: "Fleetwood Mac",
  FLIGHT_FACILITIES: "Flight Facilities",
  FLORENCE_AND_THE_MACHINE: "Florence + the Machine",
  FOREVER_THE_SICKEST_KIDS: "Forever the Sickest Kids",
  FOURS: "Fours",
  FOUR_TET: "Four Tet",
  FOXES: "Foxes",
  FRANCES: "Frances",
  FRANCIS_AND_THE_LIGHTS: "Francis and the Lights",
  FRANK_OCEAN: "Frank Ocean",
  FREYA_RIDINGS: "Freya Ridings",
  THE_FRIDAY_NIGHT_BOYS: "Friday Night Boys, The",
  FRIEND_WITHIN: "Friend Within",
  FUN_LOVIN_CRIMINALS: "Fun Lovin' Criminals",
  // G
  GABRIELLE: "Gabrielle",
  GEORGE_EZRA: "George Ezra",
  GEORGE_FITZGERALD: "George FitzGerald",
  GEORGIA: "Georgia",
  G_FLIP: "G Flip",
  GLOWIE: "Glowie",
  GORGON_CITY: "Gorgon City",
  GRACEY: "GRACEY",
  GREEN_VELVET: "Green Velvet",
  GRIMES: "Grimes",
  GROOVE_ARMADA: "Groove Armada",
  GRYFFIN: "Gryffin",
  GYM_CLASS_HEROES: "Gym Class Heroes",
  // H
  HAIM: "HAIM",
  HALSEY: "Halsey",
  HANNAH_WANTS: "Hannah Wants",
  HAUX: "Haux",
  HEIDI: "Heidi",
  HEY_MONDAY: "Hey Monday",
  HOLLY_HUMBERSTONE: "Holly Humberstone",
  HORSE_MEAT_DISCO: "Horse Meat Disco",
  // I
  INCOGNITO: "Incognito",
  // J
  JAMES_BAY: "James Bay",
  JAMES_BLAKE: "James Blake",
  JAMIE_JONES: "Jamie Jones",
  JAMIE_T: "Jamie T",
  JAMIE_XX: "Jamie xx",
  JAX_JONES: "Jax Jones",
  JAY_Z: "JAY Z",
  JEREMY_ZUCKER: "Jeremy Zucker",
  JESS_GLYNNE: "Jess Glynne",
  JESSIE_WARE: "Jessie Ware",
  JOE_GODDARD: "Joe Goddard",
  JOHNNY_MARR: "Johnny Marr",
  JONAS_BLUE: "Jonas Blue",
  JONES: "Jones",
  JON_HOPKINS: "Jon Hopkins",
  JORIS_VOORN: "Joris Voorn",
  JORJA_SMITH: "Jorja Smith",
  JOSH_BUTLER: "Josh Butler",
  JOY_ORBISON: "Joy Orbison",
  JOSEF_SALVAT: "Josef Salvat",
  JULIA_MICHAELS: "Julia Michaels",
  JULIO_BASHMORE: "Julio Bashmore",
  JUSTIN_BIEBER: "Justin Bieber",
  JUSTIN_MARTIN: "Justin Martin",
  // K
  KAH_LO: "Kah-Lo",
  KANYE_WEST: "Kanye West",
  KATE_NASH: "Kate Nash",
  KATY_PERRY: "Katy Perry",
  KAYTRANADA: "Kaytranada",
  KESHA: "Kesha",
  KIASMOS: "Kiasmos",
  KIDNAP: "Kidnap",
  KIDS_IN_GLASS_HOUSES: "Kids In Glass Houses",
  THE_KILLERS: "Killers, The",
  KIM_PETRAS: "Kim Petras",
  KOLSCH: "Kölsch",
  KYGO: "Kygo",
  // L
  LADY_GAGA: "Lady Gaga",
  LADY_STARLIGHT: "Lady Starlight",
  LANA_DEL_REY: { name: "Lana Del Rey", favourite: true },
  LANE_8: "Lane 8",
  LANY: "LANY",
  LA_ROUX: "La Roux",
  LAUV: "Lauv",
  L_DEVINE: "L Devine",
  LELAND: "Leland",
  LENNON_STELLA: "Lennon Stella",
  LEON: "LÉON",
  LILY_ALLEN: "Lily Allen",
  LISSIE: "Lissie",
  LITTLE_COMETS: "Little Comets",
  LITTLE_DRAGON: "Little Dragon",
  LONDON_GRAMMAR: "London Grammar",
  LORDE: "Lorde",
  LUCY_ROSE: "Lucy Rose",
  LYKKE_LI: "Lykke Li",
  LYVES: "Lyves",
  // M
  MACEO_PLEX: "Maceo Plex",
  MALLRAT: "Mallrat",
  MAGGIE_ROGERS: "Maggie Rogers",
  THE_MAINE: "Maine, The",
  MAJOR_LAZER: "Major Lazer",
  MARY_J_BLIGE: "Mary J. Blige",
  MARINA: "MARINA",
  MARTIN_SOLVEIG: "Martin Solveig",
  MELANIE_MARTINEZ: "Melanie Martinez",
  METRO_STATION: "Metro Station",
  MICHAEL_KIWANUKA: "Michael Kiwanuka",
  MIDLAND: "Midland",
  MIGUEL: "Miguel",
  MIKE_POSNER: "Mike Posner",
  MILEY_CYRUS: "Miley Cyrus",
  MISHA_B: "Misha B",
  M_0: "M.O",
  MK: "MK",
  MNEK: "MNEK",
  MO: "MØ",
  MUNA: "MUNA",
  MURA_MASA: "Mura Masa",
  // N
  NAAZ: "Naaz",
  NAO: "Nao",
  NASTY_CHERRY: "Nasty Cherry",
  NATASHA_BEDINGFIELD: "Natasha Bedingfield",
  NAVVY: "Navvy",
  NICKI_MINAJ: "Nicki Minaj",
  NOEL_GALLAGHERS_HIGH_FLYING_BIRDS: "Noel Gallagher's High Flying Birds",
  // O
  OH_ANNIE_OH: "Oh Annie Oh",
  OKAYWILL: "okaywill",
  // P
  PALE_WAVES: "Pale Waves",
  PALOMA_FAITH: "Paloma Faith",
  PANIC_AT_THE_DISCO: "Panic! At the Disco",
  PARAMORE: "Paramore",
  PAUL_WOOLFORD: "Paul Woolford",
  PET_SHOP_BOYS: "Pet Shop Boys",
  PHILIP_GEORGE: "Philip George",
  PRETENDERS: "Pretenders",
  // PROSPA: "Prospa",
  PVRIS: "PVRIS",
  // R
  RAINBOW_KITTEN_SURPRISE: "Rainbow Kitten Surprise",
  RALEIGH_RITCHIE: "Raleigh Ritchie",
  RALPH: "Ralph",
  REDLIGHT: "Redlight",
  RIHANNA: "Rihanna",
  RINA_SAWAYAMA: "Rina Sawayama",
  RITON: "Riton",
  RIXTON: "Rixton",
  ROBINSON: "Robinson",
  ROBYN: "Robyn",
  ROMY: "Romy",
  ROOSEVELT: "Roosevelt",
  ROUTE_94: "Route 94",
  RYN_WEAVER: { name: "Ryn Weaver", favourite: true },
  RUDIMENTAL: "Rudimental",
  RUFUS_DU_SOL: "RÜFÜS DU SOL",
  RYAN_BEATTY: "Ryan Beatty",
  // S
  SABRINA_CLAUDIO: "Sabrina Claudio",
  SAINT_JHN: "SAINt JHN",
  SAM_SMITH: "Sam Smith",
  SASHA_SLOAN: "Sasha Sloan",
  SBTRKT: "SBTRKT",
  SEEB: "Seeb",
  SEGA_BODEGA: "Sega Bodega",
  SEINABO_SEY: "Seinabo Sey",
  SEVDALIZA: "Sevdaliza",
  SIA: "Sia",
  SIGRID: "Sigrid",
  SISTER_SLEDGE: "Sister Sledge",
  SKY_FERREIRA: { name: "Sky Ferreira", favourite: true },
  SLIIMY: "Sliimy",
  SOFI_TUKKER: "Sofi Tukker",
  SOAK: "SOAK",
  SONIKKU: "SONIKKU",
  SOPHIE: "SOPHIE",
  SOPHIE_ELLIS_BEXTOR: "Sophie Ellis-Bextor",
  SOUL_WAX: "Soul Wax",
  THE_SMYTHS: "Smyths, The",
  THE_SPILL_CANVAS: "Spill Canvas, The",
  SKREAM: "Skream",
  SUNDAY_GIRL: "Sunday Girl",
  // T
  TAYLOR_SWIFT: "Taylor Swift",
  TENSNAKE: "Tensnake",
  TEN_WALLS: "Ten Walls",
  TERROR_JR: "Terror Jr",
  TOM_ODELL: "Tom Odell",
  TORI_KELLY: "Tori Kelly",
  TOURIST: "Tourist",
  TOVE_LO: "Tove Lo",
  TROYE_SIVAN: "Troye Sivan",
  TULISA: "Tulisa",
  TWENTY_ONE_PILOTS: "Twenty One Pilots",
  TWO_FEET: "Two Feet",
  TYGA: "Tyga",
  // V
  VERITE: "VÉRITÉ",
  // W
  WE_THE_KINGS: "We the Kings",
  WILL_YOUNG: "Will Young",
  // X
  THE_XX: "xx, The",
  // Y
  YEARS_AND_YEARS: "Years & Years",
  YOU_ME_AT_SIX: "You Me At Six",
  YOUSEF: "Yousef",
  // Z
  ZARA_LARSSON: "Zara Larsson"
};
