interface IRecipePhotos {
  BAKED_BEANS: IJpgSrc;
  BANANA_CAKE: IJpgSrc;
  BANG_BANG_CAULIFLOWER: IJpgSrc;
  BOLOGNESE: IJpgSrc;
  BLUEBERRY_PANCAKES: IJpgSrc;
  BROWNIES: IJpgSrc;
  CARBONARA: IJpgSrc;
  CRUMBLE: IJpgSrc;
  FLAPJACKS: IJpgSrc;
  KALE_CRISPY: IJpgSrc;
  LASAGNE: IJpgSrc;
  MASHED_POTATO: IJpgSrc;
  PORRIDGE: IJpgSrc;
  POTATO_SALAD: IJpgSrc;
  PIRI_PIRI: IJpgSrc;
  RATATOUILLE: IJpgSrc;
  ROGAN_JOSH: IJpgSrc;
  SHEPHERDS_PIE: IJpgSrc;
}
