export const MUSICIANS: IMusicians = {
  // 123
  "1975": { name: "1975, The" },
  "100_GECS": { name: "100 gecs" },
  // A
  AURORA: { name: "Aurora" },
  THE_ACADEMY_IS: { name: "Academy Is..., The" },
  ALESSIA_CARA: { name: "Alessia Cara" },
  ALEX_CHAPMAN: { name: "Alex Chapman" },
  ALL_AMERICAN_REJECTS: { name: "All-American Rejects, The" },
  ALLIE_X: { name: "Allie X" },
  ALL_TIME_LOW: { name: "All Time Low" },
  ALMA: { name: "Alma" },
  AMOS_LEE: { name: "Amos Lee" },
  ANNA_OF_THE_NORTH: { name: "Anna of the North" },
  ADELE: { name: "Adele" },
  ANASTACIA: { name: "Anastacia" },
  ANNE_MARIE: { name: "Anne-Marie" },
  AQUILO: { name: "Aquilo" },
  ARCTIC_MONKEYS: { name: "Arctic Monkeys" },
  ARIANA_GRANDA: { name: "Ariana Grande" },
  AUDITION: { name: "Audition, The" },
  // B
  BAAUER: { name: "Baauer" },
  BANANARAMA: { name: "Bananarama" },
  BANKS: { name: "Banks" },
  BASTILLE: { name: "Bastille" },
  BAYNK: { name: "BAYNK" },
  BEARS_DEN: { name: "Bear's Den" },
  BECKY_HILL: { name: "Becky Hill" },
  BEN_HOWARD: { name: "Ben Howard" },
  BETSY: { name: "Betsy" },
  BETTY_WHO: { name: "Betty Who" },
  BEYONCE: { name: "Beyoncé" },
  BICEP: { name: "Bicep" },
  BILLIE_EILISH: { name: "Billie Eilish" },
  BLACK_KIDS: { name: "Black Kids" },
  B_O_B: { name: "B.o.B" },
  BONDAX: { name: "Bondax" },
  BON_IVER: { name: "Bon Iver" },
  BONTAN: { name: "Bontan" },
  BORNS: { name: "BØRNS" },
  BOYS_LIKE_GIRLS: { name: "Boys Like Girls" },
  BLONDE: { name: "Blonde" },
  BREACH: { name: "Breach" },
  BRIGITTE_APHRODITE: { name: "Brigitte Aphrodite" },
  BRITNEY_SPEARS: { name: "Britney Spears" },
  BROODS: { name: "Broods" },
  BULOW: { name: "bülow" },
  // C
  CAMILA_CABELLO: { name: "Camila Cabello" },
  CARIBOU: { name: "Caribou" },
  CARLY_RAE_JEPSEN: { name: "Carly Rae Jepsen" },
  CARL_COX: { name: "Carl Cox" },
  CAROLINE_POLACHEK: { name: "Caroline Polachek" },
  CELESTE: { name: "Celeste" },
  CHARLI_ADAMS: { name: "Charli Adams" },
  CHARLI_XCX: { name: "Charli XCX" },
  CHARLOTTE_CHURCH: { name: "Charlotte Church" },
  CHELSEA_CUTLER: { name: "Chelsea Cutler" },
  CHEMICAL_BROTHERS: { name: "Chemical Brothers, The" },
  CHERYL: { name: "Cheryl" },
  CHLOE_X_HALLE: { name: "Chloe x Halle" },
  CHRISTINE_AND_THE_QUEENS: { name: "Christine and the Queens" },
  CHRVCHES: { name: "CHVRCHES" },
  CLAIRO: { name: "Clairo" },
  CLEAN_BANDIT: { name: "Clean Bandit" },
  COBRA_STARSHIP: { name: "Cobra Starship" },
  CODE: { name: "Code, The" },
  CRUEL_YOUTH: { name: "Cruel Youth", favourite: true },
  CUTE_IS_WHAT_WE_AIM_FOR: { name: "Cute Is What We Aim for" },
  CYRIL_HAHN: { name: "Cyril Hahn" },
  // D
  DANIEL_AVERY: { name: "Daniel Avery" },
  DAUGHTER: { name: "Daughter" },
  DAVID_RODIGAN: { name: "David Rodigan" },
  DIPLO: { name: "Diplo" },
  DISCLOSURE: { name: "Disclosure" },
  DIZZEE_RASCAL: { name: "Dizzee Rascal" },
  DRUMS: { name: "Drums, The" },
  DUKE_DUMONT: { name: "Duke Dumont" },
  DUA_LIPA: { name: "Dua Lipa" },
  DUSKY: { name: "Dusky" },
  DYLAN: { name: "Dylan" },
  // E
  EARTHEATER: { name: "Eartheater" },
  EATS_EVERYTHING: { name: "Eats Everything" },
  ELDERBROOK: { name: "Elderbrook" },
  ELIZA_DOOLITTLE: { name: "Eliza Doolittle" },
  ELLA_EYRE: { name: "Ella Eyre" },
  ELLIE_GOULDING: { name: "Ellie Goulding" },
  EMAROSA: { name: "Emarosa" },
  // F
  FALL_OUT_BOY: { name: "Fall Out Boy" },
  FKA_TWIGS: { name: "FKA twigs" },
  FLEETWOOD_MAC: { name: "Fleetwood Mac" },
  FLIGHT_FACILITIES: { name: "Flight Facilities" },
  FLORENCE_AND_THE_MACHINE: { name: "Florence + the Machine" },
  FOREVER_THE_SICKEST_KIDS: { name: "Forever the Sickest Kids" },
  FOURS: { name: "Fours" },
  FOUR_TET: { name: "Four Tet" },
  FOXES: { name: "Foxes" },
  FRANCES: { name: "Frances" },
  FRANCIS_AND_THE_LIGHTS: { name: "Francis and the Lights" },
  FRANK_OCEAN: { name: "Frank Ocean" },
  FREYA_RIDINGS: { name: "Freya Ridings" },
  THE_FRIDAY_NIGHT_BOYS: { name: "Friday Night Boys, The" },
  FRIEND_WITHIN: { name: "Friend Within" },
  FUN_LOVIN_CRIMINALS: { name: "Fun Lovin' Criminals" },
  // G
  GABRIELLE: { name: "Gabrielle" },
  GEORGE_EZRA: { name: "George Ezra" },
  GEORGE_FITZGERALD: { name: "George FitzGerald" },
  GEORGIA: { name: "Georgia" },
  G_FLIP: { name: "G Flip" },
  GLOWIE: { name: "Glowie" },
  GORGON_CITY: { name: "Gorgon City" },
  GRACEY: { name: "GRACEY" },
  GREEN_VELVET: { name: "Green Velvet" },
  GRIMES: { name: "Grimes" },
  GROOVE_ARMADA: { name: "Groove Armada" },
  GRYFFIN: { name: "Gryffin" },
  GYM_CLASS_HEROES: { name: "Gym Class Heroes" },
  // H
  HAIM: { name: "HAIM" },
  HALSEY: { name: "Halsey" },
  HANNAH_WANTS: { name: "Hannah Wants" },
  HAUX: { name: "Haux" },
  HEIDI: { name: "Heidi" },
  HEY_MONDAY: { name: "Hey Monday" },
  HOLLY_HUMBERSTONE: { name: "Holly Humberstone" },
  HORSE_MEAT_DISCO: { name: "Horse Meat Disco" },
  // I
  INCOGNITO: { name: "Incognito" },
  // J
  JAMES_BAY: { name: "James Bay" },
  JAMES_BLAKE: { name: "James Blake" },
  JAMIE_JONES: { name: "Jamie Jones" },
  JAMIE_T: { name: "Jamie T" },
  JAMIE_XX: { name: "Jamie xx" },
  JAX_JONES: { name: "Jax Jones" },
  JAY_Z: { name: "JAY Z" },
  JEREMY_ZUCKER: { name: "Jeremy Zucker" },
  JESS_GLYNNE: { name: "Jess Glynne" },
  JESSIE_WARE: { name: "Jessie Ware" },
  JOE_GODDARD: { name: "Joe Goddard" },
  JOHNNY_MARR: { name: "Johnny Marr" },
  JONAS_BLUE: { name: "Jonas Blue" },
  JONES: { name: "Jones" },
  JON_HOPKINS: { name: "Jon Hopkins" },
  JORIS_VOORN: { name: "Joris Voorn" },
  JORJA_SMITH: { name: "Jorja Smith" },
  JOSH_BUTLER: { name: "Josh Butler" },
  JOY_ORBISON: { name: "Joy Orbison" },
  JOSEF_SALVAT: { name: "Josef Salvat" },
  JULIA_MICHAELS: { name: "Julia Michaels" },
  JULIO_BASHMORE: { name: "Julio Bashmore" },
  JUSTIN_BIEBER: { name: "Justin Bieber" },
  JUSTIN_MARTIN: { name: "Justin Martin" },
  // K
  KAH_LO: { name: "Kah-Lo" },
  KANYE_WEST: { name: "Kanye West" },
  KATE_NASH: { name: "Kate Nash" },
  KATY_PERRY: { name: "Katy Perry" },
  KAYTRANADA: { name: "Kaytranada" },
  KESHA: { name: "Kesha" },
  KIASMOS: { name: "Kiasmos" },
  KIDNAP: { name: "Kidnap" },
  KIDS_IN_GLASS_HOUSES: { name: "Kids In Glass Houses" },
  THE_KILLERS: { name: "Killers, The" },
  KIM_PETRAS: { name: "Kim Petras" },
  KOLSCH: { name: "Kölsch" },
  KYGO: { name: "Kygo" },
  // L
  LADY_GAGA: { name: "Lady Gaga" },
  LADY_STARLIGHT: { name: "Lady Starlight" },
  LANA_DEL_REY: { name: "Lana Del Rey", favourite: true },
  LANE_8: { name: "Lane 8" },
  LANY: { name: "LANY" },
  LA_ROUX: { name: "La Roux" },
  LAUV: { name: "Lauv" },
  L_DEVINE: { name: "L Devine" },
  LELAND: { name: "Leland" },
  LENNON_STELLA: { name: "Lennon Stella" },
  LEON: { name: "LÉON" },
  LILY_ALLEN: { name: "Lily Allen" },
  LISSIE: { name: "Lissie" },
  LITTLE_COMETS: { name: "Little Comets" },
  LITTLE_DRAGON: { name: "Little Dragon" },
  LONDON_GRAMMAR: { name: "London Grammar" },
  LORDE: { name: "Lorde" },
  LUCY_ROSE: { name: "Lucy Rose" },
  LYKKE_LI: { name: "Lykke Li" },
  LYVES: { name: "Lyves" },
  // M
  MACEO_PLEX: { name: "Maceo Plex" },
  MALLRAT: { name: "Mallrat" },
  MAGGIE_ROGERS: { name: "Maggie Rogers" },
  THE_MAINE: { name: "Maine, The" },
  MAJOR_LAZER: { name: "Major Lazer" },
  MARY_J_BLIGE: { name: "Mary J. Blige" },
  MARINA: { name: "MARINA" },
  MARTIN_SOLVEIG: { name: "Martin Solveig" },
  MELANIE_MARTINEZ: { name: "Melanie Martinez" },
  METRO_STATION: { name: "Metro Station" },
  MICHAEL_KIWANUKA: { name: "Michael Kiwanuka" },
  MIDLAND: { name: "Midland" },
  MIGUEL: { name: "Miguel" },
  MIKE_POSNER: { name: "Mike Posner" },
  MILEY_CYRUS: { name: "Miley Cyrus" },
  MISHA_B: { name: "Misha B" },
  M_0: { name: "M.O" },
  MK: { name: "MK" },
  MNEK: { name: "MNEK" },
  MO: { name: "MØ" },
  MUNA: { name: "MUNA" },
  MURA_MASA: { name: "Mura Masa" },
  // N
  NAAZ: { name: "Naaz" },
  NAO: { name: "Nao" },
  NASTY_CHERRY: { name: "Nasty Cherry" },
  NATASHA_BEDINGFIELD: { name: "Natasha Bedingfield" },
  NAVVY: { name: "Navvy" },
  NICKI_MINAJ: { name: "Nicki Minaj" },
  NOEL_GALLAGHERS_HIGH_FLYING_BIRDS: {
    name: "Noel Gallagher's High Flying Birds"
  },
  // O
  OH_ANNIE_OH: { name: "Oh Annie Oh" },
  OKAYWILL: { name: "okaywill" },
  // P
  PALE_WAVES: { name: "Pale Waves" },
  PALOMA_FAITH: { name: "Paloma Faith" },
  PANIC_AT_THE_DISCO: { name: "Panic! At the Disco" },
  PARAMORE: { name: "Paramore" },
  PAUL_WOOLFORD: { name: "Paul Woolford" },
  PET_SHOP_BOYS: { name: "Pet Shop Boys" },
  PHILIP_GEORGE: { name: "Philip George" },
  PRETENDERS: { name: "Pretenders" },
  PVRIS: { name: "PVRIS" },
  // R
  RAINBOW_KITTEN_SURPRISE: { name: "Rainbow Kitten Surprise" },
  RALEIGH_RITCHIE: { name: "Raleigh Ritchie" },
  RALPH: { name: "Ralph" },
  REDLIGHT: { name: "Redlight" },
  RIHANNA: { name: "Rihanna" },
  RINA_SAWAYAMA: { name: "Rina Sawayama" },
  RITON: { name: "Riton" },
  RIXTON: { name: "Rixton" },
  ROBINSON: { name: "Robinson" },
  ROBYN: { name: "Robyn" },
  ROMY: { name: "Romy" },
  ROOSEVELT: { name: "Roosevelt" },
  ROUTE_94: { name: "Route 94" },
  RYN_WEAVER: { name: "Ryn Weaver", favourite: true },
  RUDIMENTAL: { name: "Rudimental" },
  RUFUS_DU_SOL: { name: "RÜFÜS DU SOL" },
  RYAN_BEATTY: { name: "Ryan Beatty" },
  // S
  SABRINA_CLAUDIO: { name: "Sabrina Claudio" },
  SAINT_JHN: { name: "SAINt JHN" },
  SAM_SMITH: { name: "Sam Smith" },
  SASHA_SLOAN: { name: "Sasha Sloan" },
  SBTRKT: { name: "SBTRKT" },
  SEEB: { name: "Seeb" },
  SEGA_BODEGA: { name: "Sega Bodega" },
  SEINABO_SEY: { name: "Seinabo Sey" },
  SEVDALIZA: { name: "Sevdaliza" },
  SIA: { name: "Sia" },
  SIGRID: { name: "Sigrid" },
  SISTER_SLEDGE: { name: "Sister Sledge" },
  SKY_FERREIRA: { name: "Sky Ferreira", favourite: true },
  SLIIMY: { name: "Sliimy" },
  SOFI_TUKKER: { name: "Sofi Tukker" },
  SOAK: { name: "SOAK" },
  SONIKKU: { name: "SONIKKU" },
  SOPHIE: { name: "SOPHIE" },
  SOPHIE_ELLIS_BEXTOR: { name: "Sophie Ellis-Bextor" },
  SOUL_WAX: { name: "Soul Wax" },
  THE_SMYTHS: { name: "Smyths, The" },
  THE_SPILL_CANVAS: { name: "Spill Canvas, The" },
  SKREAM: { name: "Skream" },
  SUNDAY_GIRL: { name: "Sunday Girl" },
  // T
  TAYLOR_SWIFT: { name: "Taylor Swift" },
  TENSNAKE: { name: "Tensnake" },
  TEN_WALLS: { name: "Ten Walls" },
  TERROR_JR: { name: "Terror Jr" },
  TOM_ODELL: { name: "Tom Odell" },
  TORI_KELLY: { name: "Tori Kelly" },
  TOURIST: { name: "Tourist" },
  TOVE_LO: { name: "Tove Lo" },
  TROYE_SIVAN: { name: "Troye Sivan" },
  TULISA: { name: "Tulisa" },
  TWENTY_ONE_PILOTS: { name: "Twenty One Pilots" },
  TWO_FEET: { name: "Two Feet" },
  TYGA: { name: "Tyga" },
  // V
  VERITE: { name: "VÉRITÉ" },
  // W
  WE_THE_KINGS: { name: "We the Kings" },
  WILL_YOUNG: { name: "Will Young" },
  // X
  THE_XX: { name: "xx, The" },
  // Y
  YEARS_AND_YEARS: { name: "Years & Years" },
  YOU_ME_AT_SIX: { name: "You Me At Six" },
  YOUSEF: { name: "Yousef" },
  // Z
  ZARA_LARSSON: { name: "Zara Larsson" }
};
