interface IActor extends INameFavourite {}

interface IActors {
  ADAM_JAMES: IActor;
  ADI_CHUGH: IActor;
  AIMEE_LOU_WOOD: IActor;
  BENJAMIN_ALUWIHARE: IActor;
  CLAIRE_FOY: IActor;
  DAVID_MOORST: IActor;
  GWENDOLINE_CHRISITE: IActor;
  HAMMED_ANIMASHAUN: IActor;
  HATTY_JONES: IActor;
  JASON_WATKINS: IActor;
  JOHN_MCCREA: IActor;
  KATHERINE_PARKINSON: IActor;
  LAURIE_KYNASTON: IActor;
  LEE_INGLEBY: IActor;
  MATT_SMITH: IActor;
  MILLY_THOMAS: IActor;
  NINA_SOSANYA: IActor;
  OLIVER_CHRIS: IActor;
  PETER_MCPHERSON: IActor;
  SARA_BAREILLES: IActor;
  SIAN_CLIFFORD: IActor;
  SURANNE_JONES: IActor;
  TIMOTHEE_CHALAMET: IActor;
}
